feat(workspace-manager): Do not show encrypted Git credentials to users
modelix/modelix.workspaces pull request #215
Opened 2024-12-13 10:52 UTC by odzhychko

Fixes: MODELIX-1060

2024-12-13 11:18 UTC, odzhychko commented on workspace-manager/src/main/kotlin/org/modelix/workspace/manager/WorkspaceManagerModule.kt
> +                        // TODO Credentials can be exposed here
We could:

* Remove the credentials from the response.
  * The `/rest` endpoints are only used in instance-manager and the credentials only in the workspace-manger.
  * We would need to change the response to provide the correct hash because without credentials the instance-manger cannot calculate the hash.
 * Protect the endpoints with a permission, that the instance-manager gets and users do not get.
 
 @slisson What solution aligns with the indented usage of the `/rest` endpoint in the future?

2024-12-13 12:10 UTC, slisson commented on workspace-manager/src/main/kotlin/org/modelix/workspace/manager/WorkspaceManagerModule.kt
> +                        // TODO Credentials can be exposed here
- There is the class `WorkspaceAndHash` exactly for the purpose that the instances-manager doesn't have to calculate the hash.
- If we do [MODELIX-1057 Merge workspace-manager and instances-manager](https://issues.modelix.org/issue/MODELIX-1057), we can remove all the endpoints that are only used by the instances-manager and reduce the attack surface.

2024-12-13 14:57 UTC, odzhychko commented on workspace-manager/src/main/kotlin/org/modelix/workspace/manager/WorkspaceManagerModule.kt
> +                        // TODO Credentials can be exposed here
Ok, the I will remove it by implementing MODELI-1057.
This PR can the be reviewed.

2024-12-15 09:25 UTC, slisson requested changes

2024-12-15 09:25 UTC, slisson commented on workspace-manager/src/main/kotlin/org/modelix/workspace/manager/WorkspaceManagerModule.kt
> +        val existingCredentials = existingWorkspaceConfig.gitRepositories.getOrNull(i)?.credentials
I would match the received and existing config by the repository URL. The user should never be able to use existing credentials for a different repository.

2024-12-15 09:25 UTC, slisson commented on workspace-manager/src/main/kotlin/org/modelix/workspace/manager/WorkspaceManagerModule.kt
> +            "Received masked user, but no previous Git credentials are known."
Just remove the credentials. Copy pasting a config should not result in an exception.

2024-12-15 09:25 UTC, slisson commented on workspace-manager/src/main/kotlin/org/modelix/workspace/manager/WorkspaceManagerModule.kt
> +            "Received masked password, but no previous Git credentials are known."
Same as for the user name.

2024-12-16 10:32 UTC, odzhychko commented on workspace-manager/src/main/kotlin/org/modelix/workspace/manager/WorkspaceManagerModule.kt
> +            "Received masked password, but no previous Git credentials are known."
done

2024-12-16 10:32 UTC, odzhychko commented on workspace-manager/src/main/kotlin/org/modelix/workspace/manager/WorkspaceManagerModule.kt
> +            "Received masked user, but no previous Git credentials are known."
done

2024-12-16 10:36 UTC, odzhychko commented on workspace-manager/src/main/kotlin/org/modelix/workspace/manager/WorkspaceManagerModule.kt
> +        val existingCredentials = existingWorkspaceConfig.gitRepositories.getOrNull(i)?.credentials
I now also check the URL after using the index.
Using the index is needed for the very rare cases, when a user has more the one repository defined with the same URL, but different credentials.

2024-12-16 10:47 UTC, slisson approved these changes

2024-12-16 10:48 UTC, merged